/**
 * Snapshot of Tailwind's PostCSS output for this gallery widget.
 * Regenerated by `npm run extract:widget-css`.
 */
export const widgetClassNames = [
  "rounded-xl",
  "bg-yellow-300",
  "px-4",
  "py-3",
  "text-zinc-950",
  "shadow-sm",
  "ring-2",
  "ring-fuchsia-600"
] as const;

export const widgetCssVariables = [
  {
    "name": "--color-fuchsia-600",
    "value": "oklch(59.1% 0.293 322.896)",
    "source": "theme"
  },
  {
    "name": "--color-yellow-300",
    "value": "oklch(90.5% 0.182 98.111)",
    "source": "theme"
  },
  {
    "name": "--color-zinc-950",
    "value": "oklch(14.1% 0.005 285.823)",
    "source": "theme"
  },
  {
    "name": "--radius-xl",
    "value": "0.75rem",
    "source": "theme"
  },
  {
    "name": "--spacing",
    "value": "0.25rem",
    "source": "theme"
  },
  {
    "name": "--tw-inset-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-inset-ring-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-ring-offset-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-ring-offset-width",
    "value": "0px",
    "source": "property"
  }
] as const;

export const widgetClassRules = [
  {
    "className": "rounded-xl",
    "css": ".rounded-xl {\n  border-radius: var(--radius-xl);\n}"
  },
  {
    "className": "bg-yellow-300",
    "css": ".bg-yellow-300 {\n  background-color: var(--color-yellow-300);\n}"
  },
  {
    "className": "px-4",
    "css": ".px-4 {\n  padding-inline: calc(var(--spacing) * 4);\n}"
  },
  {
    "className": "py-3",
    "css": ".py-3 {\n  padding-block: calc(var(--spacing) * 3);\n}"
  },
  {
    "className": "text-zinc-950",
    "css": ".text-zinc-950 {\n  color: var(--color-zinc-950);\n}"
  },
  {
    "className": "shadow-sm",
    "css": ".shadow-sm {\n  --tw-shadow: 0 1px 3px 0 var(--tw-shadow-color, rgb(0 0 0 / 0.1)), 0 1px 2px -1px var(--tw-shadow-color, rgb(0 0 0 / 0.1));\n  box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);\n}"
  },
  {
    "className": "ring-2",
    "css": ".ring-2 {\n  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);\n  box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);\n}"
  },
  {
    "className": "ring-fuchsia-600",
    "css": ".ring-fuchsia-600 {\n  --tw-ring-color: var(--color-fuchsia-600);\n}"
  }
] as const;
