/**
 * Snapshot of Tailwind's PostCSS output for this gallery widget.
 * Regenerated by `npm run extract:widget-css`.
 */
export const widgetClassNames = [
  "rounded-xl",
  "bg-parity-accent-soft",
  "px-4",
  "py-3",
  "text-parity-ink",
  "shadow-sm",
  "ring-1",
  "ring-parity-accent/30"
] as const;

export const widgetCssVariables = [
  {
    "name": "--color-parity-accent",
    "value": "#6d28d9",
    "source": "theme"
  },
  {
    "name": "--color-parity-accent-soft",
    "value": "#ede9fe",
    "source": "theme"
  },
  {
    "name": "--color-parity-ink",
    "value": "#1c1917",
    "source": "theme"
  },
  {
    "name": "--radius-xl",
    "value": "0.75rem",
    "source": "theme"
  },
  {
    "name": "--spacing",
    "value": "0.25rem",
    "source": "theme"
  },
  {
    "name": "--tw-inset-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-inset-ring-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-ring-offset-shadow",
    "value": "0 0 #0000",
    "source": "property"
  },
  {
    "name": "--tw-ring-offset-width",
    "value": "0px",
    "source": "property"
  }
] as const;

export const widgetClassRules = [
  {
    "className": "rounded-xl",
    "css": ".rounded-xl {\n  border-radius: var(--radius-xl);\n}"
  },
  {
    "className": "bg-parity-accent-soft",
    "css": ".bg-parity-accent-soft {\n  background-color: var(--color-parity-accent-soft);\n}"
  },
  {
    "className": "px-4",
    "css": ".px-4 {\n  padding-inline: calc(var(--spacing) * 4);\n}"
  },
  {
    "className": "py-3",
    "css": ".py-3 {\n  padding-block: calc(var(--spacing) * 3);\n}"
  },
  {
    "className": "text-parity-ink",
    "css": ".text-parity-ink {\n  color: var(--color-parity-ink);\n}"
  },
  {
    "className": "shadow-sm",
    "css": ".shadow-sm {\n  --tw-shadow: 0 1px 3px 0 var(--tw-shadow-color, rgb(0 0 0 / 0.1)), 0 1px 2px -1px var(--tw-shadow-color, rgb(0 0 0 / 0.1));\n  box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);\n}"
  },
  {
    "className": "ring-1",
    "css": ".ring-1 {\n  --tw-ring-shadow: var(--tw-ring-inset,) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);\n  box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);\n}"
  },
  {
    "className": "ring-parity-accent/30",
    "css": ".ring-parity-accent\\/30 {\n  --tw-ring-color: color-mix(in srgb, #6d28d9 30%, transparent);\n  @supports (color: color-mix(in lab, red, red)) {\n    --tw-ring-color: color-mix(in oklab, var(--color-parity-accent) 30%, transparent);\n  }\n}"
  }
] as const;
